# coding: utf-8

"""
    Kiln API Specifications

    This API provides reporting staking data on various protocols as well as network wide data, staking transaction crafting features and so on. In order to use it, you should first get an API token from your Kiln dashboard (applications section). If you don't have access to our dashboard, please get in touch at hello@kiln.fi. Once you have your API token, you can set it as a bearer token in your request headers.  ### Backward Compatibility  This is an experimental specification used for development and testing, do not rely on what is here unless you know the implications.  The official Kiln API specification following backward compatible changes can be found [here](/).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@kiln.fi
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class EthereumOperationDeposit(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    type: Optional[StrictStr] = Field(None, description="type of the operation")
    time: Optional[datetime] = Field(None, description="Time of the operation")
    validator_address: Optional[StrictStr] = Field(None, description="Validator address of the operation")
    tx_hash: Optional[StrictStr] = Field(None, description="Hash of the transaction")
    tx_gas_used: Optional[StrictStr] = Field(None, description="Gas used by the transaction in WEI")
    tx_sender: Optional[StrictStr] = Field(None, description="Address of the sender of the transaction")
    proxies: Optional[List[StrictStr]] = Field(None, description="Ordered list of smart-contracts in the calling chain")
    block: Optional[StrictInt] = Field(None, description="Block number containing the transaction")
    withdrawal_credentials: Optional[StrictStr] = Field(None, description="Withdrawal credentials of the deposit")
    amount: Optional[StrictStr] = Field(None, description="Amount in WEI of the deposit transaction")
    __properties = ["type", "time", "validator_address", "tx_hash", "tx_gas_used", "tx_sender", "proxies", "block", "withdrawal_credentials", "amount"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EthereumOperationDeposit:
        """Create an instance of EthereumOperationDeposit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EthereumOperationDeposit:
        """Create an instance of EthereumOperationDeposit from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return EthereumOperationDeposit.parse_obj(obj)

        _obj = EthereumOperationDeposit.parse_obj({
            "type": obj.get("type"),
            "time": obj.get("time"),
            "validator_address": obj.get("validator_address"),
            "tx_hash": obj.get("tx_hash"),
            "tx_gas_used": obj.get("tx_gas_used"),
            "tx_sender": obj.get("tx_sender"),
            "proxies": obj.get("proxies"),
            "block": obj.get("block"),
            "withdrawal_credentials": obj.get("withdrawal_credentials"),
            "amount": obj.get("amount")
        })
        return _obj

