# coding: utf-8

"""
    Kiln Connect

    This API provides reporting staking data on various protocols as well as network wide data, staking transaction crafting features and so on.  In order to use it, you should first get an API token from your Kiln dashboard (applications section). If you don't have access to our dashboard, please get in touch at hello@kiln.fi.  Once you have your API token, you can set it as a bearer token in your request headers.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@kiln.fi
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.ethereum_broadcast_tx_response import EthereumBroadcastTxResponse  # noqa: E501
from openapi_client.rest import ApiException

class TestEthereumBroadcastTxResponse(unittest.TestCase):
    """EthereumBroadcastTxResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EthereumBroadcastTxResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EthereumBroadcastTxResponse`
        """
        model = openapi_client.models.ethereum_broadcast_tx_response.EthereumBroadcastTxResponse()  # noqa: E501
        if include_optional :
            return EthereumBroadcastTxResponse(
                tx_hash = ''
            )
        else :
            return EthereumBroadcastTxResponse(
        )
        """

    def testEthereumBroadcastTxResponse(self):
        """Test EthereumBroadcastTxResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
