# coding: utf-8

"""
    Kiln Connect

    This API provides reporting staking data on various protocols as well as network wide data, staking transaction crafting features and so on.  In order to use it, you should first get an API token from your Kiln dashboard (applications section). If you don't have access to our dashboard, please get in touch at hello@kiln.fi.  Once you have your API token, you can set it as a bearer token in your request headers.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@kiln.fi
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.eth_api import EthApi  # noqa: E501
from openapi_client.rest import ApiException


class TestEthApi(unittest.TestCase):
    """EthApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.eth_api.EthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_eth_network_stats(self):
        """Test case for get_eth_network_stats

        Network stats  # noqa: E501
        """
        pass

    def test_get_eth_operations(self):
        """Test case for get_eth_operations

        Operations  # noqa: E501
        """
        pass

    def test_get_eth_report(self):
        """Test case for get_eth_report

        Report  # noqa: E501
        """
        pass

    def test_get_eth_rewards(self):
        """Test case for get_eth_rewards

        Rewards  # noqa: E501
        """
        pass

    def test_get_eth_stake_transaction_status(self):
        """Test case for get_eth_stake_transaction_status

        Transaction status  # noqa: E501
        """
        pass

    def test_get_eth_stakes(self):
        """Test case for get_eth_stakes

        Ethereum stakes  # noqa: E501
        """
        pass

    def test_post_eth_stake_transaction(self):
        """Test case for post_eth_stake_transaction

        Stake creation  # noqa: E501
        """
        pass

    def test_post_eth_transaction_broadcast(self):
        """Test case for post_eth_transaction_broadcast

        Transaction broadcast  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
