# coding: utf-8

"""
    Kiln Connect

    This API provides reporting staking data on various protocols as well as network wide data, staking transaction crafting features and so on.  In order to use it, you should first get an API token from your Kiln dashboard (applications section). If you don't have access to our dashboard, please get in touch at hello@kiln.fi.  Once you have your API token, you can set it as a bearer token in your request headers.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: contact@kiln.fi
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.v1_eth_transaction_status.get import GetEthStakeTransactionStatus
from openapi_client.paths.v1_eth_network_stats.get import GetEthereumNetworkStats
from openapi_client.paths.v1_eth_operations.get import GetEthereumOperations
from openapi_client.paths.v1_eth_reports.get import GetEthereumReport
from openapi_client.paths.v1_eth_rewards.get import GetEthereumRewards
from openapi_client.paths.v1_eth_stakes.get import GetEthereumStakes
from openapi_client.paths.v1_eth_transaction_stake.post import PostEthStakeTransaction
from openapi_client.paths.v1_eth_transaction_broadcast.post import PostEthTransactionBroadcast


class ETHApi(
    GetEthStakeTransactionStatus,
    GetEthereumNetworkStats,
    GetEthereumOperations,
    GetEthereumReport,
    GetEthereumRewards,
    GetEthereumStakes,
    PostEthStakeTransaction,
    PostEthTransactionBroadcast,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
